import { Injectable } from '@nestjs/common';
import { InjectDataSource } from '@nestjs/typeorm';
import axios from 'axios';
import { DataSource } from 'typeorm';

export interface VoiceTextRequest {
  text?: string;
  audioBase64?: string;
  audioMimeType?: string;
  fileName?: string;
}

export interface AgentReply {
  text: string;
  sql?: string;
  result?: any;
  raw?: any;
}

@Injectable()
export class OllamaAssistantService {
  private readonly ollamaUrl = process.env.OLLAMA_URL || 'http://localhost:11434/api/chat';
  private readonly model = process.env.OLLAMA_MODEL || 'qwen3:8b';
  private readonly whisperUrl = process.env.WHISPER_URL;

  constructor(@InjectDataSource() private readonly dataSource?: DataSource) {}

  async handleUserRequest(input: VoiceTextRequest): Promise<AgentReply> {
    const userText = await this.normalizeInput(input);

    if (!userText?.trim()) {
      throw new Error('No text input received');
    }

    const sql = await this.generateSqlOnly(userText);

    if (!this.dataSource) {
      return {
        text: 'SQL generated successfully',
        sql,
      };
    }

    const result = await this.dataSource.query(sql);

    return {
      text: 'SQL generated and executed successfully',
      sql,
      result,
    };
  }

  async generateSqlOnly(text?: string): Promise<string> {
    const userText = (text || '').trim();

    if (!userText) {
      throw new Error('No text input received');
    }

    const schemaContext = await this.getSchemaContext();
    const systemPrompt = `You are a PostgreSQL SQL generator for this application.
Use ONLY the database schema provided below.
Do not invent table names, column names, or aliases.
Convert the user's request into exactly one valid SQL statement.
Return only SQL, no explanation, no markdown, no extra text.
If the request is ambiguous, return a safe SELECT query.
Always use PostgreSQL syntax.

Database schema:
${schemaContext || 'No schema information available.'}`;

    const response = await axios.post(
      this.ollamaUrl,
      {
        model: this.model,
        messages: [
          {
            role: 'system',
            content: `${systemPrompt}\n\nSafety rules:\n- Only generate SELECT queries.\n- Never use DROP, DELETE, UPDATE, INSERT, ALTER, TRUNCATE, or UNION.\n- If the request is unsafe, return SELECT 1 as safe_query;`,
          },
          {
            role: 'user',
            content: userText,
          },
        ],
        stream: false,
      },
      {
        headers: {
          'Content-Type': 'application/json',
        },
      },
    );

    const sql = this.extractSql(response.data?.message?.content || '');

    if (!sql) {
      throw new Error('No SQL was generated by the model');
    }

    const normalizedSql = sql.trim().replace(/;$|\s+/g, ' ');

    if (!this.isSafeSelectQuery(normalizedSql)) {
      throw new Error('Generated SQL is not safe');
    }

    return normalizedSql;
  }

  private async normalizeInput(input: VoiceTextRequest): Promise<string> {
    if (input.text?.trim()) {
      return input.text.trim();
    }

    if (input.audioBase64) {
      if (!this.whisperUrl) {
        throw new Error('Voice input is enabled but WHISPER_URL is not configured');
      }

      const transcription = await this.transcribeAudio(
        input.audioBase64,
        input.audioMimeType || 'audio/webm',
        input.fileName,
      );

      return transcription;
    }

    return '';
  }

  private async transcribeAudio(
    audioBase64: string,
    mimeType: string,
    fileName?: string,
  ): Promise<string> {
    try {
      const response = await axios.post(
        this.whisperUrl!,
        {
          audioBase64,
          mimeType,
          fileName,
        },
        {
          headers: {
            'Content-Type': 'application/json',
          },
        },
      );

      return response.data?.text?.trim() || '';
    } catch (error: any) {
      throw new Error(`Audio transcription failed: ${error?.message || 'unknown error'}`);
    }
  }

  private async getSchemaContext(): Promise<string> {
    if (!this.dataSource) {
      return '';
    }

    try {
      const tables = await this.dataSource.query(
        `SELECT table_name
         FROM information_schema.tables
         WHERE table_schema = 'public' AND table_type = 'BASE TABLE'
         ORDER BY table_name`,
      );

      const lines: string[] = [];
      for (const table of tables) {
        const tableName = table.table_name;
        const columns = await this.dataSource.query(
          `SELECT column_name, data_type, is_nullable, column_default
           FROM information_schema.columns
           WHERE table_schema = 'public' AND table_name = $1
           ORDER BY ordinal_position`,
          [tableName],
        );

        const columnLines = columns.map((column: any) => {
          const nullable = column.is_nullable === 'YES' ? 'NULL' : 'NOT NULL';
          return `${column.column_name} ${column.data_type} ${nullable}`;
        });

        lines.push(`- ${tableName}: ${columnLines.join(', ')}`);
      }

      return lines.join('\n');
    } catch (error) {
      return '';
    }
  }

  private isSafeSelectQuery(sql: string): boolean {
    const forbidden = /\b(DROP|DELETE|UPDATE|INSERT|ALTER|TRUNCATE|CREATE|GRANT|REVOKE|EXEC|UNION|JOIN|WITH)\b/i;
    const normalized = sql.trim().toUpperCase();

    if (!normalized.startsWith('SELECT')) {
      return false;
    }

    if (forbidden.test(normalized)) {
      return false;
    }

    return true;
  }

  private extractSql(content: string): string {
    const cleaned = content.trim();
    const match = cleaned.match(/SELECT[\s\S]+/i);
    return (match?.[0] || cleaned).trim().replace(/```sql|```/gi, '').trim();
  }
}
