import { MigrationInterface, QueryRunner } from "typeorm";

export class InitDb1751193824570 implements MigrationInterface {
    name = 'InitDb1751193824570'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "StoreDispatchHeaderStatusHistories" ("Id" BIGSERIAL NOT NULL, "Status" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "StoreDispatchHeaderId" bigint, "UserId" uuid, CONSTRAINT "PK_f02eab45db13b35fdb05489a68f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreDispatchHeaderStatusHistories_pkey" ON "StoreDispatchHeaderStatusHistories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "StoreReceiptHeaders" ("Id" BIGSERIAL NOT NULL, "Code" character varying(10) NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "StoreId" bigint, "UserId" uuid, CONSTRAINT "PK_e34e0c3c7c613fefb0a4d94690b" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreReceiptHeaders_pkey" ON "StoreReceiptHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "StoreTransactions" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "Operation" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "Destruction" boolean, "AdminConfirm" boolean NOT NULL, "AdminUserId" uuid, "ItemId" bigint, "StoreDispatchDetailId" bigint, "StoreId" bigint, "StoreReceiptDetailId" bigint, "UserId" uuid, CONSTRAINT "PK_cebd018779839598220d485854c" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreTransactions_pkey" ON "StoreTransactions" ("Id") `);
        await queryRunner.query(`CREATE TABLE "LeaveHistories" ("Id" BIGSERIAL NOT NULL, "Description" character varying, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "LeaveId" bigint, "UserId" uuid, CONSTRAINT "PK_4af81b1a3bf14d37eb0662a4910" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "LeaveHistories_pkey" ON "LeaveHistories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Leaves" ("Id" BIGSERIAL NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIME WITH TIME ZONE NOT NULL, "Status" smallint NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "PersonnelId" bigint, "UserId" uuid, CONSTRAINT "PK_511f30fb90886809257cd357dac" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Leaves_pkey" ON "Leaves" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Consignments" ("Id" BIGSERIAL NOT NULL, "Name" character varying NOT NULL, "Code" character varying NOT NULL, "PlaceId" bigint, "PlaceType" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_363ec4595c52128c24ac0480fab" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Consignments_pkey" ON "Consignments" ("Id") `);
        await queryRunner.query(`CREATE TABLE "PersonnelConsigneds" ("Id" BIGSERIAL NOT NULL, "AssignmentDate" TIME WITH TIME ZONE, "CreateAt" TIME WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "ReturnDate" TIMESTAMP WITH TIME ZONE, "Attachments" json, "ConsignmentId" bigint, "ParentId" bigint, "PersonnelId" bigint, "UserId" uuid, CONSTRAINT "PK_5aa9bb8b68887376439d521063f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "PersonnelConsigneds_pkey" ON "PersonnelConsigneds" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Positions" ("Id" BIGSERIAL NOT NULL, "Ttile" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_12cfcf6b51cf64ba39224fd4227" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Positions_pkey" ON "Positions" ("Id") `);
        await queryRunner.query(`CREATE TABLE "UserSystemOperations" ("Id" BIGSERIAL NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "MainUserId" uuid, "SystemOperationId" bigint, "UserId" uuid, CONSTRAINT "PK_2be54126442126b9807b1d5b72d" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UserSystemOperations_pkey" ON "UserSystemOperations" ("Id") `);
        await queryRunner.query(`CREATE TABLE "SystemOperations" ("Id" BIGSERIAL NOT NULL, "Name" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_38fd2a5190363b767dc2495478b" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "SystemOperations_pkey" ON "SystemOperations" ("Id") `);
        await queryRunner.query(`CREATE TABLE "RoleSystemOperations" ("Id" BIGSERIAL NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RoleId" bigint, "SystemOperationId" bigint, "UserId" uuid, CONSTRAINT "PK_4a685a44c6e7c577bf29e671270" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "RoleSystemOperations_pkey" ON "RoleSystemOperations" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Roles" ("Id" BIGSERIAL NOT NULL, "Name" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_04f7be88261f9d1e55675c0ee75" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Roles_pkey" ON "Roles" ("Id") `);
        await queryRunner.query(`CREATE TABLE "UserRoles" ("Id" BIGSERIAL NOT NULL, "CreateAt" TIME WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "AssigendUserId" uuid, "RoleId" bigint, "UserId" uuid, CONSTRAINT "PK_2167a51985d902b272f362b062d" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UserRoles_pkey" ON "UserRoles" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ForceMajors" ("Id" BIGSERIAL NOT NULL, "Ttitle" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_8d3d21d8b880d75b96a6c1ba1c6" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ForceMajors_pkey" ON "ForceMajors" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ProjectPlanningImplementation" ("Id" BIGSERIAL NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "KaziYapilanDirekSayisi" json, "AltMontajiYapilanDirekSayisi" json, "BetonAtilanDirekSayisi" json, "UstMontajiOrulenDirekSayisi" json, "UstMontajiKurulanDirekSayisi" json, "DikilenBetonDirekSayisi" json, "IletkenCekilenDirekSayisi" json, "AyiriciTakilanDirekSayisi" json, "DikilenAydinlatmaDirekSayisi" json, "KabloKanali" json, "CekilenKabloMiktari" json, "Transformator" json, "DagitimPanosu" json, "SahaDagıtımKutusu" json, "BetonKosk" json, "Hucre" json, "Description" character varying, "PlanningStatus" smallint, "ForceMajorId" bigint, "ProjectPlanningId" bigint, "UserId" uuid, CONSTRAINT "PK_55a9963c6491350ad6bbba13b3c" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ProjectPlanningImplementation_pkey" ON "ProjectPlanningImplementation" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ProjectPlanings" ("Id" BIGSERIAL NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "KaziYapilanDirekSayisi" smallint, "AltMontajiYapilanDirekSayisi" smallint, "BetonAtilanDirekSayisi" smallint, "UstMontajiOrulenDirekSayisi" smallint, "UstMontajiKurulanDirekSayisi" smallint, "DikilenBetonDirekSayisi" smallint, "IletkenCekilenDirekSayisi" smallint, "AyiriciTakilanDirekSayisi" smallint, "DikilenAydinlatmaDirekSayisi" smallint, "KabloKanali" integer, "CekilenKabloMiktari" integer, "Transformator" smallint, "DagitimPanosu" smallint, "SahaDagıtımKutusu" smallint, "BetonKosk" smallint, "Hucre" smallint, "ProjectId" bigint, "UserId" uuid, CONSTRAINT "PK_4f2e90d75aa0423a2f888e57928" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ProjectPlanings_pkey" ON "ProjectPlanings" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ProjectFirms" ("Id" BIGSERIAL NOT NULL, "Ttitle" character varying NOT NULL, "Abbreviation" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_dc71832ffdcfdd09ddc2103a3d4" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ProjectFirms_pkey" ON "ProjectFirms" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Projects" ("Id" BIGSERIAL NOT NULL, "Title" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE, "PredictEndDate" TIMESTAMP WITH TIME ZONE, "EndDate" TIMESTAMP WITH TIME ZONE, "Type" smallint, "Code" character varying(20), "ProjectFirmId" bigint, "UserId" uuid, "WorkhouseId" bigint, CONSTRAINT "PK_1e9e8e45af53624c913b916489f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Projects_pkey" ON "Projects" ("Id") `);
        await queryRunner.query(`CREATE TABLE "PersonnelWorkplaceProjects" ("Id" BIGSERIAL NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE, "ProjectStatus" smallint NOT NULL, "ProjectStatusDescription" character varying, "PersonnelWorkPlaceId" bigint, "ProjectId" bigint, "UserId" uuid, CONSTRAINT "PK_97ce8d25bc034bebe4587842514" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "PersonnelWorkplaceProjects_pkey" ON "PersonnelWorkplaceProjects" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Rollcalls" ("Id" BIGSERIAL NOT NULL, "Date" TIMESTAMP WITH TIME ZONE NOT NULL, "StartTime" TIME, "EndTime" TIME, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "PersonnelWorkPlaceId" bigint, "UserId" uuid, CONSTRAINT "PK_ebe5a79a887e0b16d6a4cc1778d" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Rollcalls_pkey" ON "Rollcalls" ("Id") `);
        await queryRunner.query(`CREATE TABLE "PersonnelWorkPlaces" ("Id" BIGSERIAL NOT NULL, "PlaceId" bigint NOT NULL, "Type" bigint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDate" TIMESTAMP WITH TIME ZONE, "WorkStatus" smallint NOT NULL, "WorkStatusDescription" character varying, "PersonnelId" bigint, "PositionId" bigint, "UserId" uuid, "UserRoleId" bigint, CONSTRAINT "PK_ba4548ddf8f5ba8371f52467746" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "PersonnelWorkPlaces_pkey" ON "PersonnelWorkPlaces" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Personnels" ("Id" BIGSERIAL NOT NULL, "Name" character varying(250) NOT NULL, "Family" character varying(250) NOT NULL, "IdentityNumber" character varying(11) NOT NULL, "WorkStartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "WorkEndDate" TIMESTAMP WITH TIME ZONE, "InsuranceNumber" character varying(20), "Sex" smallint NOT NULL, "SalaryType" smallint NOT NULL, "SalaryAccrualMethod" smallint NOT NULL, "Group" smallint NOT NULL, "BirthPlace" character varying(320), "BirthDate" TIMESTAMP WITH TIME ZONE NOT NULL, "MaritalStatus" smallint, "FatherName" character varying(150) NOT NULL, "BloodType" smallint, "Address" character varying NOT NULL, "EducationStatus" smallint NOT NULL, "IBAN" character varying, "Telephone" character varying, "Mobile" character varying, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "PositionId" bigint, "UserId" uuid, CONSTRAINT "PK_45d8defdc48c99c22b46f37f03a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Personnels_pkey" ON "Personnels" ("Id") `);
        await queryRunner.query(`CREATE TABLE "CourseParticipants" ("Id" BIGSERIAL NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "IsParticipated" boolean NOT NULL, "RecordStatus" smallint NOT NULL, "CourseId" bigint, "PersonnelId" bigint, "UserId" uuid, CONSTRAINT "PK_a47d6fdeb1e39b5fddac35b7976" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "CourseParticipants_pkey" ON "CourseParticipants" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Teachers" ("Id" BIGSERIAL NOT NULL, "Name" bigint NOT NULL, "Surname" character varying NOT NULL, "Field" character varying, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "UserId" uuid, CONSTRAINT "PK_5ce831fb01e9c174bfbe7b13267" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Teachers_pkey" ON "Teachers" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Courses" ("Id" BIGSERIAL NOT NULL, "Title" character varying NOT NULL, "Description" character varying, "StartDateTime" TIMESTAMP WITH TIME ZONE NOT NULL, "EndDateTime" TIME WITH TIME ZONE, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "Attachments" json NOT NULL, "TeacherId" bigint, "UserId" uuid, "WorkhouseId" bigint, CONSTRAINT "PK_7941ffc9b08a6b86e4ea65df622" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Courses_pkey" ON "Courses" ("Id") `);
        await queryRunner.query(`CREATE TABLE "WarehouseDispatchHeaderStatusHistories" ("Id" BIGSERIAL NOT NULL, "Status" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid NOT NULL, "Description" character varying, "WarehouseDispatchHeaderId" bigint, CONSTRAINT "PK_6f46a63de2b4d124b5a929d27de" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "WarehouseDispatchHeaderStatusHistories_pkey" ON "WarehouseDispatchHeaderStatusHistories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "WarehouseTransactions" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "Operation" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "Firm" boolean NOT NULL, "Destruction" boolean, "AdminConfirm" boolean, "AdminUserId" uuid, "ItemId" bigint, "ProviderId" bigint, "ReceiptDetailId" bigint, "UserId" uuid, "WarehouseDispatchDetailId" bigint, "WarehouseId" bigint, CONSTRAINT "PK_37f0decb42d7d7db5660cf89d22" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "WarehouseTransactions_pkey" ON "WarehouseTransactions" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Warehouses" ("Id" BIGSERIAL NOT NULL, "Name" character varying(150) NOT NULL, "Code" character varying(10) NOT NULL, "Address" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "RegionId" bigint, "UserId" uuid, CONSTRAINT "PK_ffd66a2c8a5e712076ab29209a0" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Warehouses_pkey" ON "Warehouses" ("Id") `);
        await queryRunner.query(`CREATE TABLE "DriverVehicles" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Model" integer NOT NULL, "Plaque" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "DriverId" bigint, "UserId" uuid, CONSTRAINT "PK_f34e35bb91b5d74407213e5fa49" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "DriverVehicles_pkey" ON "DriverVehicles" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Drivers" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Family" character varying(200) NOT NULL, "Birthdate" TIMESTAMP WITH TIME ZONE, "FatherName" character varying, "IdentityNo" character varying(11) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Internal" boolean NOT NULL, "UserId" uuid, CONSTRAINT "PK_2442b154fa97579ad0e3f270ddd" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Drivers_pkey" ON "Drivers" ("Id") `);
        await queryRunner.query(`CREATE TABLE "WarehouseDispatchHeaders" ("Id" BIGSERIAL NOT NULL, "Code" character varying(10) NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Status" smallint NOT NULL, "StatusDescription" character varying, "DestinationWarehouseId" bigint, "DriverId" bigint, "UserId" uuid, "WarehouseId" bigint, "WorkhouseId" bigint, CONSTRAINT "PK_ac9f3f4579a9470ac721a776d5c" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "WarehouseDispatchHeaders_pkey" ON "WarehouseDispatchHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "WorkhouseDetails" ("Id" BIGSERIAL NOT NULL, "Owner" character varying(200) NOT NULL, "RentStartDate" TIMESTAMP WITH TIME ZONE NOT NULL, "RentEndDate" TIMESTAMP WITH TIME ZONE NOT NULL, "Price" money NOT NULL, "Subscription" json NOT NULL, "Description" character varying, "Attachments" json, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, "WorkhouseId" bigint, CONSTRAINT "PK_31133c563729f92f51d1d5c0449" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "WorkhouseDetails_pkey" ON "WorkhouseDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Workhouses" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Code" character varying(10) NOT NULL, "Address" character varying, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "RegionId" bigint, "UserId" uuid, "WorkId" bigint, CONSTRAINT "PK_ff5f0dbeabf2573e6569569af38" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Workhouses_pkey" ON "Workhouses" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Stores" ("Id" BIGSERIAL NOT NULL, "Name" character varying(150) NOT NULL, "Code" character varying(10) NOT NULL, "Address" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "RegionId" bigint, "UserId" uuid, "WorkhouseId" bigint, CONSTRAINT "PK_05faf7407b8def69cf764682eed" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Stores_pkey" ON "Stores" ("Id") `);
        await queryRunner.query(`CREATE TABLE "StoreDispatchHeaders" ("Id" BIGSERIAL NOT NULL, "Code" character varying(10) NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Destruction" boolean, "Status" smallint NOT NULL, "StatusDescription" character varying, "DestinationStoreId" bigint, "DestinationWarehouseId" bigint, "DriverId" bigint, "StoreId" bigint, "UserId" uuid, CONSTRAINT "PK_18f384f645fef4f80290a0307b8" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreDispatchHeaders_pkey" ON "StoreDispatchHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "StoreDispatchDetails" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "ItemId" bigint, "StoreDispatchHeadersId" bigint, "UserId" uuid, CONSTRAINT "PK_306663112572c0b053d52249a43" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreDispatchDetails_pkey" ON "StoreDispatchDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "StoreReceiptDetails" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Destruction" boolean, "Attachments" json, "Description" character varying, "ItemId" bigint, "StoreDispatchDetailId" bigint, "StoreReceiptHeaderId" bigint, "UserId" uuid, "WarehouseDispatchDetailId" bigint, CONSTRAINT "PK_109257c9a64c3d1b8b6d89e237f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "StoreReceiptDetails_pkey" ON "StoreReceiptDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "WarehouseDispatchDetails" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "ItemId" bigint, "UserId" uuid, "WarehouseDispatchHeadersId" bigint, CONSTRAINT "PK_1f06ec16fe0b54bd0c3655c84fe" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "WarehouseDispatchDetails_pkey" ON "WarehouseDispatchDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ReceiptHeaders" ("Id" BIGSERIAL NOT NULL, "Code" character varying(10) NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_b800a3248bb1571890ceb22716a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ReceiptHeaders_pkey" ON "ReceiptHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ReceiptDetails" ("Id" BIGSERIAL NOT NULL, "ItemId" bigint NOT NULL, "Quantity" numeric(10,2) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Firm" boolean, "Description" character varying, "InvoiceDetailId" bigint, "OriginWarehouseDispatchDeatailId" bigint, "ProviderId" bigint, "ReceiptHeaderId" bigint, "StoreDispatchDetailId" bigint, "UserId" uuid, CONSTRAINT "PK_04de958b6e97198bbdfba468a26" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ReceiptDetails_pkey" ON "ReceiptDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Providers" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Address" character varying NOT NULL, "Phone" character varying, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Firm" boolean, "RegionId" bigint, "UserId" uuid, CONSTRAINT "PK_121071fab0040634c58a8bb6225" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Providers_pkey" ON "Providers" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Regions" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "ParentId" bigint, "UserId" uuid, CONSTRAINT "PK_0a6de20d302e8ad3bd4908567f9" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Regions_pkey" ON "Regions" ("Id") `);
        await queryRunner.query(`CREATE TABLE "CarWarhouses" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Code" character varying(10) NOT NULL, "Address" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "RegionId" bigint, "UserId" uuid, CONSTRAINT "PK_298d98f84b2b64324ade057e468" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "CarWarhouses_pkey" ON "CarWarhouses" ("Id") `);
        await queryRunner.query(`CREATE TABLE "CarWarhouseDetails" ("Id" BIGSERIAL NOT NULL, "Brand" character varying(200) NOT NULL, "Model" character varying NOT NULL, "ManufactureDate" TIMESTAMP WITH TIME ZONE NOT NULL, "Plaque" character varying NOT NULL, "Attacments" json NOT NULL, "Description" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Available" boolean NOT NULL, "CarWarhouseId" bigint, "UserId" uuid, CONSTRAINT "PK_aaf8431cb90a19afff6c0375f0c" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "CarWarhouseDetails_pkey" ON "CarWarhouseDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ConsignedCars" ("Id" BIGSERIAL NOT NULL, "Date" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Consigned" boolean NOT NULL, "Attachments" json NOT NULL, "Description" character varying, "Kilometer" integer NOT NULL, "CarWarhouseDetailId" bigint, "PersonnelId" bigint, "UserId" uuid, CONSTRAINT "PK_06dc7c8f4ebf5638b69252606b3" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ConsignedCars_pkey" ON "ConsignedCars" ("Id") `);
        await queryRunner.query(`CREATE TABLE "CarFuels" ("Id" BIGSERIAL NOT NULL, "Date" TIMESTAMP WITH TIME ZONE NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "FuelType" character varying NOT NULL, "Amount" smallint NOT NULL, "Description" character varying, "Fee" money NOT NULL, "TotatPrice" money NOT NULL, "Attachment" json, "ConsignedCarId" bigint, "UserId" uuid, CONSTRAINT "PK_2bb18de719a88d6d64162bbcda8" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "CarFuels_pkey" ON "CarFuels" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Categories" ("Id" BIGSERIAL NOT NULL, "Name" character varying(200) NOT NULL, "Depth" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "ParentId" bigint, "UserId" uuid, CONSTRAINT "PK_04ba3e718fe1c234e75a30c457a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Categories_pkey" ON "Categories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ItemUnits" ("Id" BIGSERIAL NOT NULL, "Title" character varying NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "UserId" uuid, CONSTRAINT "PK_31a92f4a061978b035ddbd8d889" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ItemUnits_pkey" ON "ItemUnits" ("Id") `);
        await queryRunner.query(`CREATE TABLE "OrderDetails" ("Id" BIGSERIAL NOT NULL, "Quantity" numeric(10,2) NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "ItemId" bigint, "OrderHeaderId" bigint, "UserId" uuid, CONSTRAINT "PK_02a8ce7f8cfd60c6aa69e0cb216" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "OrderDetails_pkey" ON "OrderDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "OrderHeaderStatusHistories" ("Id" BIGSERIAL NOT NULL, "Status" smallint NOT NULL, "Description" character varying, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "OrderHeaderId" bigint, "UserId" uuid, CONSTRAINT "PK_3530a27c46054911718d34c3cf5" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "OrderHeaderStatusHistories_pkey" ON "OrderHeaderStatusHistories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "OrderHeaders" ("Id" BIGSERIAL NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "Status" smallint NOT NULL, "NetworkId" bigint, "UserId" uuid, CONSTRAINT "PK_4e6034c42d9d1b566c07381e039" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "OrderHeaders_pkey" ON "OrderHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "TransmissionRowItmes" ("Id" BIGSERIAL NOT NULL, "Value" numeric(10,2) NOT NULL, "CreateAt" TIME WITH TIME ZONE NOT NULL, "RecordStatus" smallint, "ItemId" bigint, "TransmissionRowId" bigint, "UserId" uuid, CONSTRAINT "PK_b821218e70c18399e6bdb4d7630" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TransmissionRowItmes_pkey" ON "TransmissionRowItmes" ("Id") `);
        await queryRunner.query(`CREATE TABLE "TransmissionRows" ("Id" BIGSERIAL NOT NULL, "Distance" integer NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "ProductStatus" smallint NOT NULL, "FormulaTitle" character varying NOT NULL, "FromProductTypeId" bigint, "NetworkId" bigint, "ToProductTypeId" bigint, "UserId" uuid, CONSTRAINT "PK_a14572aae8f31a567096d5b5a1a" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TransmissionRows_pkey" ON "TransmissionRows" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Networks" ("Id" BIGSERIAL NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint, "Description" character varying, "UserId" uuid, "WorkId" bigint, CONSTRAINT "PK_8daec4d84fd4ac6e2b88b5787b0" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Networks_pkey" ON "Networks" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ProductTypes" ("Id" BIGSERIAL NOT NULL, "Name" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_a4a49639063f388a3a709948b12" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ProductTypes_pkey" ON "ProductTypes" ("Id") `);
        await queryRunner.query(`CREATE TABLE "TenderHeaders" ("Id" BIGSERIAL NOT NULL, "Title" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Status" smallint, "StatusDate" TIMESTAMP WITH TIME ZONE, "UserId" uuid, CONSTRAINT "PK_b21e9c392ae094c56df7b75c2d5" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TenderHeaders_pkey" ON "TenderHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "TenderDetails" ("Id" BIGSERIAL NOT NULL, "FirmProcuredItemQuantities" numeric(10,2) NOT NULL, "OurProcuredItemQuantities" numeric(10,2) NOT NULL, "Demontaj" numeric(10,2) NOT NULL, "DemontajMontaj" numeric(10,2) NOT NULL, "FirmProcuredItemPrice" money NOT NULL, "OurProcuredItemPrice" money, "MontajPrice" money NOT NULL, "DemontajPrice" money NOT NULL, "DemontajMontajPrice" money NOT NULL, "RecordStatus" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "ItemId" bigint, "TenderHeaderId" bigint, "UserId" uuid, CONSTRAINT "PK_b519dea728ea6eaf2a258d31d38" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "TenderDetails_pkey" ON "TenderDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Users" ("Id" uuid NOT NULL DEFAULT uuid_generate_v4(), "Username" character varying(150) NOT NULL, "Password" character varying NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "UserId" uuid, CONSTRAINT "PK_329bb2946729a51bd2b19a5159f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Users_pkey" ON "Users" ("Id") `);
        await queryRunner.query(`CREATE TABLE "InvoiceHeaderStatusHistories" ("Id" BIGSERIAL NOT NULL, "Status" smallint NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "InvoiceHeaderId" bigint, "UserId" uuid, CONSTRAINT "PK_5d5c0b126372968d61fe8cb4b82" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "InvoiceHeaderStatusHistories_pkey" ON "InvoiceHeaderStatusHistories" ("Id") `);
        await queryRunner.query(`CREATE TABLE "InvoiceHeaders" ("Id" BIGSERIAL NOT NULL, "DocDate" TIMESTAMP WITH TIME ZONE NOT NULL, "TotalPrice" money NOT NULL, "TotalNetPrice" money NOT NULL, "TotalDiscount" money NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "Status" smallint NOT NULL, "StatusDescription" character varying, "DriverId" bigint, "ProviderId" bigint, "UserId" uuid, CONSTRAINT "PK_f779903b52d320d61ca178d6282" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "InvoiceHeaders_pkey" ON "InvoiceHeaders" ("Id") `);
        await queryRunner.query(`CREATE TABLE "InvoiceDetails" ("Id" BIGSERIAL NOT NULL, "quantity" numeric(10,2), "Price" money NOT NULL, "TotalPrice" money NOT NULL, "DiscountPercent" numeric(10,2) NOT NULL, "DiscountAmount" money NOT NULL, "TotalDiscount" money NOT NULL, "TotalNetPrice" money NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Description" character varying, "InvoiceHeaderId" bigint, "ItemId" bigint, "OrderDetailId" bigint, "UserId" uuid, CONSTRAINT "PK_1bee2b6f8a3e6ccdf95ee760a85" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "InvoiceDetails_pkey" ON "InvoiceDetails" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Items" ("Id" BIGSERIAL NOT NULL, "Name" character varying NOT NULL, "Description" character varying, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "Abbreviation" character varying(4) NOT NULL, "CategoryId" bigint, "UnitId" bigint, "UserId" uuid, CONSTRAINT "PK_d444b385a47acde1d7abfbe7154" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Items_pkey" ON "Items" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ChannelRowItems" ("Id" BIGSERIAL NOT NULL, "Value" numeric(10,2) NOT NULL, "CreateAt" TIME WITH TIME ZONE NOT NULL, "RecordStatus" smallint, "ChannelRowId" bigint, "ItemId" bigint, "UserId" uuid, CONSTRAINT "PK_44922ccb75f9b7157a3cc503b26" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ChannelRowItems_pkey" ON "ChannelRowItems" ("Id") `);
        await queryRunner.query(`CREATE TABLE "ChannelRows" ("Id" BIGSERIAL NOT NULL, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "ProductStatus" smallint NOT NULL, "Title" character varying NOT NULL, "Label" character varying NOT NULL, "NetworkId" bigint, "ParentId" bigint, "ProductTypeId" bigint, "ProjectId" bigint, "UserId" uuid, "WorkhouseId" bigint, CONSTRAINT "PK_e3065865a0a21101d79026aa3da" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "ChannelRows_pkey" ON "ChannelRows" ("Id") `);
        await queryRunner.query(`CREATE TABLE "Works" ("Id" BIGSERIAL NOT NULL, "Title" character varying NOT NULL, "StartDate" TIMESTAMP WITH TIME ZONE, "EndDate" TIMESTAMP WITH TIME ZONE, "CreateAt" TIMESTAMP WITH TIME ZONE NOT NULL, "RecordStatus" smallint NOT NULL, "TenderId" bigint, "UserId" uuid, CONSTRAINT "PK_b56c55223a56d67fdad16c4404f" PRIMARY KEY ("Id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "Works_pkey" ON "Works" ("Id") `);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaderStatusHistories" ADD CONSTRAINT "FK_2ae4752c69cd9582e8515d62e2c" FOREIGN KEY ("StoreDispatchHeaderId") REFERENCES "StoreDispatchHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaderStatusHistories" ADD CONSTRAINT "FK_4f0b014783bb229a7fbdacbceaa" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptHeaders" ADD CONSTRAINT "FK_06419874f370dd380f6dcd1d1ab" FOREIGN KEY ("StoreId") REFERENCES "Stores"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptHeaders" ADD CONSTRAINT "FK_2a173697761b0b9c4e507bb9f66" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_10e775973ac6d58d0e57b563d68" FOREIGN KEY ("AdminUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_7fc960b55134f8214a4fe0c29fd" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_a0e7a6704be3e518ee9df935bcd" FOREIGN KEY ("StoreDispatchDetailId") REFERENCES "StoreDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_037533bef9cbe522cd83e91cc70" FOREIGN KEY ("StoreId") REFERENCES "Stores"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_886b3f368735726761671b3abd9" FOREIGN KEY ("StoreReceiptDetailId") REFERENCES "StoreReceiptDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" ADD CONSTRAINT "FK_af233c3227588996ced5fa80dc5" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LeaveHistories" ADD CONSTRAINT "FK_5d64bceaf7c06f3a973231151de" FOREIGN KEY ("LeaveId") REFERENCES "Leaves"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "LeaveHistories" ADD CONSTRAINT "FK_299ca76dbb9bdd886d3dcdee2c8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Leaves" ADD CONSTRAINT "FK_f2ea6ae585f729f7782dc40ca90" FOREIGN KEY ("PersonnelId") REFERENCES "Personnels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Leaves" ADD CONSTRAINT "FK_cec0c2d5020277c44de6a7f7744" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Consignments" ADD CONSTRAINT "FK_9d41b6aad95b828d60f8cc3ba6f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" ADD CONSTRAINT "FK_f00ee557831be09903a41ea9df7" FOREIGN KEY ("ConsignmentId") REFERENCES "Consignments"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" ADD CONSTRAINT "FK_023b594fc4cf6f4a6464d64f5da" FOREIGN KEY ("ParentId") REFERENCES "PersonnelConsigneds"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" ADD CONSTRAINT "FK_df7e970fa20232a30c493e02452" FOREIGN KEY ("PersonnelId") REFERENCES "Personnels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" ADD CONSTRAINT "FK_95cb5143392e65e3bc67a399bc8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Positions" ADD CONSTRAINT "FK_f7d5a37a2c74d1841f0f04cf83a" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" ADD CONSTRAINT "FK_74e6fb75c28608713a2f50f1f9c" FOREIGN KEY ("MainUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" ADD CONSTRAINT "FK_0fe1d63425a53a2d6e0c90eb156" FOREIGN KEY ("SystemOperationId") REFERENCES "SystemOperations"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" ADD CONSTRAINT "FK_98369e843cc1f1e8dd768c9b0e0" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "SystemOperations" ADD CONSTRAINT "FK_b4c9f3fc0e013d1f8a8abf095a0" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" ADD CONSTRAINT "FK_ac37f5e143c3b1c9b08b37bb080" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" ADD CONSTRAINT "FK_b0fe379e79d224cb3eee2fa51ba" FOREIGN KEY ("SystemOperationId") REFERENCES "SystemOperations"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" ADD CONSTRAINT "FK_6f81cd79160862327230e1a08e8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Roles" ADD CONSTRAINT "FK_0edd9210272a77125e1fd27487e" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_c077e3fb81ccfcb9288697e1656" FOREIGN KEY ("AssigendUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_eebd61741964d948d277e831c4c" FOREIGN KEY ("RoleId") REFERENCES "Roles"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "UserRoles" ADD CONSTRAINT "FK_bd9e34313e9bb51d8b448f48f5c" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ForceMajors" ADD CONSTRAINT "FK_717de6afef77504351ecba241e8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" ADD CONSTRAINT "FK_5ff3d4f1919c33f65dbb4601d1c" FOREIGN KEY ("ForceMajorId") REFERENCES "ForceMajors"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" ADD CONSTRAINT "FK_c300cb927306e03def7b19c0721" FOREIGN KEY ("ProjectPlanningId") REFERENCES "ProjectPlanings"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" ADD CONSTRAINT "FK_4404b264a9dee6cf67ff46aa4ed" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanings" ADD CONSTRAINT "FK_83cbf8c9c8304741c63fd7ffcfe" FOREIGN KEY ("ProjectId") REFERENCES "Projects"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanings" ADD CONSTRAINT "FK_09be9a39c8284a424fc8dd16d3f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProjectFirms" ADD CONSTRAINT "FK_9a10a829949ceaa7a06df72e19c" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Projects" ADD CONSTRAINT "FK_e8e2c96209b04158e75144a818c" FOREIGN KEY ("ProjectFirmId") REFERENCES "ProjectFirms"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Projects" ADD CONSTRAINT "FK_3586429252eb163412d2050e428" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Projects" ADD CONSTRAINT "FK_192d055806a34b9ddeb9b57e398" FOREIGN KEY ("WorkhouseId") REFERENCES "Workhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" ADD CONSTRAINT "FK_f924b5897182bbd669359f45e08" FOREIGN KEY ("PersonnelWorkPlaceId") REFERENCES "PersonnelWorkPlaces"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" ADD CONSTRAINT "FK_1405427fa5a8cb9d05f55e722ad" FOREIGN KEY ("ProjectId") REFERENCES "Projects"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" ADD CONSTRAINT "FK_eb1a7bad33ba73d864bdc7abdd1" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Rollcalls" ADD CONSTRAINT "FK_6ddd14193427fda89adac1d0222" FOREIGN KEY ("PersonnelWorkPlaceId") REFERENCES "PersonnelWorkPlaces"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Rollcalls" ADD CONSTRAINT "FK_ecd705c0ace0b5ba311d7080c6d" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" ADD CONSTRAINT "FK_bd94893b9f1bce11deadf720f82" FOREIGN KEY ("PersonnelId") REFERENCES "Personnels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" ADD CONSTRAINT "FK_b99e020a4dbd6ae3faad9bf623a" FOREIGN KEY ("PositionId") REFERENCES "Positions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" ADD CONSTRAINT "FK_3c008e6d62328418bf077557fcd" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" ADD CONSTRAINT "FK_275f31e70efca4fd2c1deda8e98" FOREIGN KEY ("UserRoleId") REFERENCES "UserRoles"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Personnels" ADD CONSTRAINT "FK_6a33d281e251271dc27541024a4" FOREIGN KEY ("PositionId") REFERENCES "Positions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Personnels" ADD CONSTRAINT "FK_66ab253e19118c601f2b6c7bb63" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" ADD CONSTRAINT "FK_f227b8dd24547aad38315da4363" FOREIGN KEY ("CourseId") REFERENCES "Courses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" ADD CONSTRAINT "FK_96f33fcd95c12cee9be38e96eef" FOREIGN KEY ("PersonnelId") REFERENCES "Personnels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" ADD CONSTRAINT "FK_26475b404b7f5b51b9c62742cd0" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Teachers" ADD CONSTRAINT "FK_75c37917feecd381cc81daf6e0c" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Courses" ADD CONSTRAINT "FK_6a493e08c64ac2d8bc1b04410d5" FOREIGN KEY ("TeacherId") REFERENCES "Teachers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Courses" ADD CONSTRAINT "FK_ac4a39922892d1cdef24b5ae958" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Courses" ADD CONSTRAINT "FK_3dcb058a5ce8ce52b9125183ff1" FOREIGN KEY ("WorkhouseId") REFERENCES "Workhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaderStatusHistories" ADD CONSTRAINT "FK_500a306a3420581ea944cc33622" FOREIGN KEY ("WarehouseDispatchHeaderId") REFERENCES "WarehouseDispatchHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_27e7064020bfec40f1276e925cf" FOREIGN KEY ("AdminUserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_16bc25a3768d5768e540136e6b5" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_4c41d98e50f6b572f56271b027d" FOREIGN KEY ("ProviderId") REFERENCES "Providers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_e140ee76a77cff17dcd7c7f35f6" FOREIGN KEY ("ReceiptDetailId") REFERENCES "ReceiptDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_88a7467202367e2eca2bf02ba0a" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_2eff86a49d8235e2a38b6641861" FOREIGN KEY ("WarehouseDispatchDetailId") REFERENCES "WarehouseDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" ADD CONSTRAINT "FK_eaaf4085b89bf6ec4b1be465a1d" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Warehouses" ADD CONSTRAINT "FK_313ea1d0c1741d0c8722d4a1e02" FOREIGN KEY ("RegionId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Warehouses" ADD CONSTRAINT "FK_45cad077fe74dd6efe199865c65" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverVehicles" ADD CONSTRAINT "FK_0c7d25eb04b9b73a6f59237deae" FOREIGN KEY ("DriverId") REFERENCES "Drivers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "DriverVehicles" ADD CONSTRAINT "FK_f3f402fb120140e77068ecd8980" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Drivers" ADD CONSTRAINT "FK_6f5323d19a6c07966acd7c4d7bc" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" ADD CONSTRAINT "FK_7f9e51747cba37678a3bb3bf9d7" FOREIGN KEY ("DestinationWarehouseId") REFERENCES "Warehouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" ADD CONSTRAINT "FK_6ab00799c19d207b9a62b7c0bb5" FOREIGN KEY ("DriverId") REFERENCES "Drivers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" ADD CONSTRAINT "FK_b205778044722b0a603d2316a21" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" ADD CONSTRAINT "FK_75667baaf300eade1ed94e7b71b" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" ADD CONSTRAINT "FK_24e8d3cf7b72e727de6a9454a06" FOREIGN KEY ("WorkhouseId") REFERENCES "Workhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WorkhouseDetails" ADD CONSTRAINT "FK_be8e407ef91e3047c6d570826a8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WorkhouseDetails" ADD CONSTRAINT "FK_3804b3ee589580863fb099ecce4" FOREIGN KEY ("WorkhouseId") REFERENCES "Workhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Workhouses" ADD CONSTRAINT "FK_9f2167560740b8237352fbf2964" FOREIGN KEY ("RegionId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Workhouses" ADD CONSTRAINT "FK_8d544bcacfeee8f2d2eee4840bf" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Workhouses" ADD CONSTRAINT "FK_4b73f5caf47940ef50b2344d54b" FOREIGN KEY ("WorkId") REFERENCES "Works"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Stores" ADD CONSTRAINT "FK_99ea66e7ddd0f8657fe7339b7c3" FOREIGN KEY ("RegionId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Stores" ADD CONSTRAINT "FK_fc30277a77c30430b435d2a7989" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Stores" ADD CONSTRAINT "FK_5ae535ead4e4183d7c74cf3cf66" FOREIGN KEY ("WorkhouseId") REFERENCES "Workhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" ADD CONSTRAINT "FK_91edfae22870ea90bbebd7fc421" FOREIGN KEY ("DestinationStoreId") REFERENCES "Stores"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" ADD CONSTRAINT "FK_1e76a8099001e004f9bb58931ce" FOREIGN KEY ("DestinationWarehouseId") REFERENCES "Warehouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" ADD CONSTRAINT "FK_fdf9508090d7bcb0d439e53acbc" FOREIGN KEY ("DriverId") REFERENCES "Drivers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" ADD CONSTRAINT "FK_0c7dbe32f00c84a488cd0b3ed0f" FOREIGN KEY ("StoreId") REFERENCES "Stores"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" ADD CONSTRAINT "FK_a32bc13accb7fb0fd43cd8ccde8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" ADD CONSTRAINT "FK_d9ebb99e3d11135e2930412921d" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" ADD CONSTRAINT "FK_abebf60abc9c301f8b0f9bcd542" FOREIGN KEY ("StoreDispatchHeadersId") REFERENCES "StoreDispatchHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" ADD CONSTRAINT "FK_b56db76b89448f70b4f035a49b8" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" ADD CONSTRAINT "FK_1e466625c22ff0f78f82461622b" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" ADD CONSTRAINT "FK_2f4e27e45b19ebf7c56d8caa4bc" FOREIGN KEY ("StoreDispatchDetailId") REFERENCES "StoreDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" ADD CONSTRAINT "FK_8a2eb27a5eb86505a86872fa2b2" FOREIGN KEY ("StoreReceiptHeaderId") REFERENCES "StoreReceiptHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" ADD CONSTRAINT "FK_9ffd24cc138ed607bb209670054" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" ADD CONSTRAINT "FK_74505c4df14a61b8d9d4627f84b" FOREIGN KEY ("WarehouseDispatchDetailId") REFERENCES "WarehouseDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" ADD CONSTRAINT "FK_ea5d36bb9c7452fa60a220b2fa1" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" ADD CONSTRAINT "FK_4fa5760fa69b74d9ef4da3442e5" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" ADD CONSTRAINT "FK_03d879a1d8e177371badfd08ccc" FOREIGN KEY ("WarehouseDispatchHeadersId") REFERENCES "WarehouseDispatchHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptHeaders" ADD CONSTRAINT "FK_bc33f93dce95e63dde0b6845e39" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_b61d442090d7261ada103754b5e" FOREIGN KEY ("InvoiceDetailId") REFERENCES "InvoiceDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_75ffe4d849140ad95ff17d998c1" FOREIGN KEY ("OriginWarehouseDispatchDeatailId") REFERENCES "WarehouseDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_8d836e699e6faf4bb49b077b2eb" FOREIGN KEY ("ProviderId") REFERENCES "Providers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_f1f76658bd193b8fec13c8aeb3f" FOREIGN KEY ("ReceiptHeaderId") REFERENCES "ReceiptHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_3835f685f6938bc10c483b1d476" FOREIGN KEY ("StoreDispatchDetailId") REFERENCES "StoreDispatchDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" ADD CONSTRAINT "FK_57d92548bce60364ba1bfca4b73" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Providers" ADD CONSTRAINT "FK_c7767698132462c9e4a6c122884" FOREIGN KEY ("RegionId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Providers" ADD CONSTRAINT "FK_7429740a43c71888e03627b9d0f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Regions" ADD CONSTRAINT "FK_2f83f3c0409dfadc3ae234b6342" FOREIGN KEY ("ParentId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Regions" ADD CONSTRAINT "FK_b324fa6a7752e54e905ea16edeb" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarWarhouses" ADD CONSTRAINT "FK_a50409fc3c3ba46bf20d5f3b584" FOREIGN KEY ("RegionId") REFERENCES "Regions"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarWarhouses" ADD CONSTRAINT "FK_f0825a4598b0dd963a022bf6203" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarWarhouseDetails" ADD CONSTRAINT "FK_f7c80fb59f3b3dd982be5f1ccfd" FOREIGN KEY ("CarWarhouseId") REFERENCES "CarWarhouses"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarWarhouseDetails" ADD CONSTRAINT "FK_3273dd989338d6e84d31de65627" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" ADD CONSTRAINT "FK_0e1606d74fc5a1b752037c9c782" FOREIGN KEY ("CarWarhouseDetailId") REFERENCES "CarWarhouseDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" ADD CONSTRAINT "FK_15e2840a9d86e6140e16f8da169" FOREIGN KEY ("PersonnelId") REFERENCES "Personnels"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" ADD CONSTRAINT "FK_016a03b5de37661c56cce45a58b" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarFuels" ADD CONSTRAINT "FK_ccc885db3746116f3fa2d350192" FOREIGN KEY ("ConsignedCarId") REFERENCES "ConsignedCars"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "CarFuels" ADD CONSTRAINT "FK_1cd104d4337306aa3fc420e1837" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Categories" ADD CONSTRAINT "FK_f684c93209de27402c77c668760" FOREIGN KEY ("ParentId") REFERENCES "Categories"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Categories" ADD CONSTRAINT "FK_ab115fdcbd15aa0c6aa6846fe7f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ItemUnits" ADD CONSTRAINT "FK_c069b465b8400b0c5a19193f83a" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_7ab5706bc744bde611e9f7def82" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_e0cced4b39ea6c8e0c69901801d" FOREIGN KEY ("OrderHeaderId") REFERENCES "OrderHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" ADD CONSTRAINT "FK_353de42eb6a6e2412a0bdbeb29a" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderHeaderStatusHistories" ADD CONSTRAINT "FK_34da10a200abdf957a3924a8c9f" FOREIGN KEY ("OrderHeaderId") REFERENCES "OrderHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderHeaderStatusHistories" ADD CONSTRAINT "FK_c3b23487be817983cd5d609866c" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderHeaders" ADD CONSTRAINT "FK_fc47ed1f85753297045199fa1b3" FOREIGN KEY ("NetworkId") REFERENCES "Networks"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "OrderHeaders" ADD CONSTRAINT "FK_489a0a666d998e1f8e2474be801" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" ADD CONSTRAINT "FK_4d775f599c50ec3f8e5116abd6d" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" ADD CONSTRAINT "FK_654212450dfba89439431def36d" FOREIGN KEY ("TransmissionRowId") REFERENCES "TransmissionRows"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" ADD CONSTRAINT "FK_bdb9127821e705a88c8b9a7180f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" ADD CONSTRAINT "FK_8c2e6e8547c9633a1333d4fca85" FOREIGN KEY ("FromProductTypeId") REFERENCES "ChannelRows"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" ADD CONSTRAINT "FK_65e639a5a247db321afe6ab6a5f" FOREIGN KEY ("NetworkId") REFERENCES "Networks"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" ADD CONSTRAINT "FK_cbef3d6dd63b63c2807fdd09568" FOREIGN KEY ("ToProductTypeId") REFERENCES "ChannelRows"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" ADD CONSTRAINT "FK_2e7f45acfc7cc605d1b5a2d30f1" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Networks" ADD CONSTRAINT "FK_170b853dd2d323ae601113ff4f1" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Networks" ADD CONSTRAINT "FK_fff0fde6a51a5dbf97ed96eb722" FOREIGN KEY ("WorkId") REFERENCES "Works"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ProductTypes" ADD CONSTRAINT "FK_9fc272925176c5469b54398d195" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TenderHeaders" ADD CONSTRAINT "FK_656280e4e8ef84394f22300e208" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" ADD CONSTRAINT "FK_d89a6921614f27943b6c041c389" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" ADD CONSTRAINT "FK_200232106450570e67d6c3d9c44" FOREIGN KEY ("TenderHeaderId") REFERENCES "TenderHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" ADD CONSTRAINT "FK_7b46ee4b43a3736551bdc8b2b4d" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaderStatusHistories" ADD CONSTRAINT "FK_40e1ba89ccfbedb560347a86b83" FOREIGN KEY ("InvoiceHeaderId") REFERENCES "InvoiceHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaderStatusHistories" ADD CONSTRAINT "FK_434d42cedc8bb494e15ddaefe62" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" ADD CONSTRAINT "FK_23603034f1c7e8b27ec06636189" FOREIGN KEY ("DriverId") REFERENCES "Drivers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" ADD CONSTRAINT "FK_ed14fa61955523cf1cee0a5bd20" FOREIGN KEY ("ProviderId") REFERENCES "Providers"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" ADD CONSTRAINT "FK_2e84ac16bde64deee4c78d83233" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" ADD CONSTRAINT "FK_e9121b45b3b94c70f1210c92727" FOREIGN KEY ("InvoiceHeaderId") REFERENCES "InvoiceHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" ADD CONSTRAINT "FK_7daa1ca31e2b0fadcb28638f1a3" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" ADD CONSTRAINT "FK_5a089b443e7de1bb23f8a510024" FOREIGN KEY ("OrderDetailId") REFERENCES "OrderDetails"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" ADD CONSTRAINT "FK_be33d722ae421b2e387cd204744" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Items" ADD CONSTRAINT "FK_86de84b4b9beb08e926283737f0" FOREIGN KEY ("CategoryId") REFERENCES "Categories"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Items" ADD CONSTRAINT "FK_c3d3cc14b86e65a8146c97fc8f7" FOREIGN KEY ("UnitId") REFERENCES "ItemUnits"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Items" ADD CONSTRAINT "FK_518a3f713e0285d6ad2b77ab5cd" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" ADD CONSTRAINT "FK_d83e6c1584801f6fd327056d71a" FOREIGN KEY ("ChannelRowId") REFERENCES "ChannelRows"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" ADD CONSTRAINT "FK_e2cf52d361e6970f537210dd3b2" FOREIGN KEY ("ItemId") REFERENCES "Items"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" ADD CONSTRAINT "FK_039504872f35b8d44562959d22a" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_11c30ad7353d0db46809468820f" FOREIGN KEY ("NetworkId") REFERENCES "Networks"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_12acaabbacde24e61099b037be2" FOREIGN KEY ("ParentId") REFERENCES "ChannelRows"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_16fda021f014932f1c45909e5fa" FOREIGN KEY ("ProductTypeId") REFERENCES "ProductTypes"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_0b7df40b3e4d8e80c032802aa56" FOREIGN KEY ("ProjectId") REFERENCES "Projects"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_cea8286ebc451585d58a294151f" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" ADD CONSTRAINT "FK_e2c51a82180ee2fc521211a6528" FOREIGN KEY ("WorkhouseId") REFERENCES "Works"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Works" ADD CONSTRAINT "FK_e0a3ff67869ce9be27f3bd44e50" FOREIGN KEY ("TenderId") REFERENCES "TenderHeaders"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "Works" ADD CONSTRAINT "FK_2b7768ab8509dc92cb457fbb8cb" FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "Works" DROP CONSTRAINT "FK_2b7768ab8509dc92cb457fbb8cb"`);
        await queryRunner.query(`ALTER TABLE "Works" DROP CONSTRAINT "FK_e0a3ff67869ce9be27f3bd44e50"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_e2c51a82180ee2fc521211a6528"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_cea8286ebc451585d58a294151f"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_0b7df40b3e4d8e80c032802aa56"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_16fda021f014932f1c45909e5fa"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_12acaabbacde24e61099b037be2"`);
        await queryRunner.query(`ALTER TABLE "ChannelRows" DROP CONSTRAINT "FK_11c30ad7353d0db46809468820f"`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" DROP CONSTRAINT "FK_039504872f35b8d44562959d22a"`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" DROP CONSTRAINT "FK_e2cf52d361e6970f537210dd3b2"`);
        await queryRunner.query(`ALTER TABLE "ChannelRowItems" DROP CONSTRAINT "FK_d83e6c1584801f6fd327056d71a"`);
        await queryRunner.query(`ALTER TABLE "Items" DROP CONSTRAINT "FK_518a3f713e0285d6ad2b77ab5cd"`);
        await queryRunner.query(`ALTER TABLE "Items" DROP CONSTRAINT "FK_c3d3cc14b86e65a8146c97fc8f7"`);
        await queryRunner.query(`ALTER TABLE "Items" DROP CONSTRAINT "FK_86de84b4b9beb08e926283737f0"`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" DROP CONSTRAINT "FK_be33d722ae421b2e387cd204744"`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" DROP CONSTRAINT "FK_5a089b443e7de1bb23f8a510024"`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" DROP CONSTRAINT "FK_7daa1ca31e2b0fadcb28638f1a3"`);
        await queryRunner.query(`ALTER TABLE "InvoiceDetails" DROP CONSTRAINT "FK_e9121b45b3b94c70f1210c92727"`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" DROP CONSTRAINT "FK_2e84ac16bde64deee4c78d83233"`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" DROP CONSTRAINT "FK_ed14fa61955523cf1cee0a5bd20"`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaders" DROP CONSTRAINT "FK_23603034f1c7e8b27ec06636189"`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaderStatusHistories" DROP CONSTRAINT "FK_434d42cedc8bb494e15ddaefe62"`);
        await queryRunner.query(`ALTER TABLE "InvoiceHeaderStatusHistories" DROP CONSTRAINT "FK_40e1ba89ccfbedb560347a86b83"`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" DROP CONSTRAINT "FK_7b46ee4b43a3736551bdc8b2b4d"`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" DROP CONSTRAINT "FK_200232106450570e67d6c3d9c44"`);
        await queryRunner.query(`ALTER TABLE "TenderDetails" DROP CONSTRAINT "FK_d89a6921614f27943b6c041c389"`);
        await queryRunner.query(`ALTER TABLE "TenderHeaders" DROP CONSTRAINT "FK_656280e4e8ef84394f22300e208"`);
        await queryRunner.query(`ALTER TABLE "ProductTypes" DROP CONSTRAINT "FK_9fc272925176c5469b54398d195"`);
        await queryRunner.query(`ALTER TABLE "Networks" DROP CONSTRAINT "FK_fff0fde6a51a5dbf97ed96eb722"`);
        await queryRunner.query(`ALTER TABLE "Networks" DROP CONSTRAINT "FK_170b853dd2d323ae601113ff4f1"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" DROP CONSTRAINT "FK_2e7f45acfc7cc605d1b5a2d30f1"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" DROP CONSTRAINT "FK_cbef3d6dd63b63c2807fdd09568"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" DROP CONSTRAINT "FK_65e639a5a247db321afe6ab6a5f"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRows" DROP CONSTRAINT "FK_8c2e6e8547c9633a1333d4fca85"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" DROP CONSTRAINT "FK_bdb9127821e705a88c8b9a7180f"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" DROP CONSTRAINT "FK_654212450dfba89439431def36d"`);
        await queryRunner.query(`ALTER TABLE "TransmissionRowItmes" DROP CONSTRAINT "FK_4d775f599c50ec3f8e5116abd6d"`);
        await queryRunner.query(`ALTER TABLE "OrderHeaders" DROP CONSTRAINT "FK_489a0a666d998e1f8e2474be801"`);
        await queryRunner.query(`ALTER TABLE "OrderHeaders" DROP CONSTRAINT "FK_fc47ed1f85753297045199fa1b3"`);
        await queryRunner.query(`ALTER TABLE "OrderHeaderStatusHistories" DROP CONSTRAINT "FK_c3b23487be817983cd5d609866c"`);
        await queryRunner.query(`ALTER TABLE "OrderHeaderStatusHistories" DROP CONSTRAINT "FK_34da10a200abdf957a3924a8c9f"`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" DROP CONSTRAINT "FK_353de42eb6a6e2412a0bdbeb29a"`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" DROP CONSTRAINT "FK_e0cced4b39ea6c8e0c69901801d"`);
        await queryRunner.query(`ALTER TABLE "OrderDetails" DROP CONSTRAINT "FK_7ab5706bc744bde611e9f7def82"`);
        await queryRunner.query(`ALTER TABLE "ItemUnits" DROP CONSTRAINT "FK_c069b465b8400b0c5a19193f83a"`);
        await queryRunner.query(`ALTER TABLE "Categories" DROP CONSTRAINT "FK_ab115fdcbd15aa0c6aa6846fe7f"`);
        await queryRunner.query(`ALTER TABLE "Categories" DROP CONSTRAINT "FK_f684c93209de27402c77c668760"`);
        await queryRunner.query(`ALTER TABLE "CarFuels" DROP CONSTRAINT "FK_1cd104d4337306aa3fc420e1837"`);
        await queryRunner.query(`ALTER TABLE "CarFuels" DROP CONSTRAINT "FK_ccc885db3746116f3fa2d350192"`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" DROP CONSTRAINT "FK_016a03b5de37661c56cce45a58b"`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" DROP CONSTRAINT "FK_15e2840a9d86e6140e16f8da169"`);
        await queryRunner.query(`ALTER TABLE "ConsignedCars" DROP CONSTRAINT "FK_0e1606d74fc5a1b752037c9c782"`);
        await queryRunner.query(`ALTER TABLE "CarWarhouseDetails" DROP CONSTRAINT "FK_3273dd989338d6e84d31de65627"`);
        await queryRunner.query(`ALTER TABLE "CarWarhouseDetails" DROP CONSTRAINT "FK_f7c80fb59f3b3dd982be5f1ccfd"`);
        await queryRunner.query(`ALTER TABLE "CarWarhouses" DROP CONSTRAINT "FK_f0825a4598b0dd963a022bf6203"`);
        await queryRunner.query(`ALTER TABLE "CarWarhouses" DROP CONSTRAINT "FK_a50409fc3c3ba46bf20d5f3b584"`);
        await queryRunner.query(`ALTER TABLE "Regions" DROP CONSTRAINT "FK_b324fa6a7752e54e905ea16edeb"`);
        await queryRunner.query(`ALTER TABLE "Regions" DROP CONSTRAINT "FK_2f83f3c0409dfadc3ae234b6342"`);
        await queryRunner.query(`ALTER TABLE "Providers" DROP CONSTRAINT "FK_7429740a43c71888e03627b9d0f"`);
        await queryRunner.query(`ALTER TABLE "Providers" DROP CONSTRAINT "FK_c7767698132462c9e4a6c122884"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_57d92548bce60364ba1bfca4b73"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_3835f685f6938bc10c483b1d476"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_f1f76658bd193b8fec13c8aeb3f"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_8d836e699e6faf4bb49b077b2eb"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_75ffe4d849140ad95ff17d998c1"`);
        await queryRunner.query(`ALTER TABLE "ReceiptDetails" DROP CONSTRAINT "FK_b61d442090d7261ada103754b5e"`);
        await queryRunner.query(`ALTER TABLE "ReceiptHeaders" DROP CONSTRAINT "FK_bc33f93dce95e63dde0b6845e39"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" DROP CONSTRAINT "FK_03d879a1d8e177371badfd08ccc"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" DROP CONSTRAINT "FK_4fa5760fa69b74d9ef4da3442e5"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchDetails" DROP CONSTRAINT "FK_ea5d36bb9c7452fa60a220b2fa1"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" DROP CONSTRAINT "FK_74505c4df14a61b8d9d4627f84b"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" DROP CONSTRAINT "FK_9ffd24cc138ed607bb209670054"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" DROP CONSTRAINT "FK_8a2eb27a5eb86505a86872fa2b2"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" DROP CONSTRAINT "FK_2f4e27e45b19ebf7c56d8caa4bc"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptDetails" DROP CONSTRAINT "FK_1e466625c22ff0f78f82461622b"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" DROP CONSTRAINT "FK_b56db76b89448f70b4f035a49b8"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" DROP CONSTRAINT "FK_abebf60abc9c301f8b0f9bcd542"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchDetails" DROP CONSTRAINT "FK_d9ebb99e3d11135e2930412921d"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" DROP CONSTRAINT "FK_a32bc13accb7fb0fd43cd8ccde8"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" DROP CONSTRAINT "FK_0c7dbe32f00c84a488cd0b3ed0f"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" DROP CONSTRAINT "FK_fdf9508090d7bcb0d439e53acbc"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" DROP CONSTRAINT "FK_1e76a8099001e004f9bb58931ce"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaders" DROP CONSTRAINT "FK_91edfae22870ea90bbebd7fc421"`);
        await queryRunner.query(`ALTER TABLE "Stores" DROP CONSTRAINT "FK_5ae535ead4e4183d7c74cf3cf66"`);
        await queryRunner.query(`ALTER TABLE "Stores" DROP CONSTRAINT "FK_fc30277a77c30430b435d2a7989"`);
        await queryRunner.query(`ALTER TABLE "Stores" DROP CONSTRAINT "FK_99ea66e7ddd0f8657fe7339b7c3"`);
        await queryRunner.query(`ALTER TABLE "Workhouses" DROP CONSTRAINT "FK_4b73f5caf47940ef50b2344d54b"`);
        await queryRunner.query(`ALTER TABLE "Workhouses" DROP CONSTRAINT "FK_8d544bcacfeee8f2d2eee4840bf"`);
        await queryRunner.query(`ALTER TABLE "Workhouses" DROP CONSTRAINT "FK_9f2167560740b8237352fbf2964"`);
        await queryRunner.query(`ALTER TABLE "WorkhouseDetails" DROP CONSTRAINT "FK_3804b3ee589580863fb099ecce4"`);
        await queryRunner.query(`ALTER TABLE "WorkhouseDetails" DROP CONSTRAINT "FK_be8e407ef91e3047c6d570826a8"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" DROP CONSTRAINT "FK_24e8d3cf7b72e727de6a9454a06"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" DROP CONSTRAINT "FK_75667baaf300eade1ed94e7b71b"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" DROP CONSTRAINT "FK_b205778044722b0a603d2316a21"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" DROP CONSTRAINT "FK_6ab00799c19d207b9a62b7c0bb5"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaders" DROP CONSTRAINT "FK_7f9e51747cba37678a3bb3bf9d7"`);
        await queryRunner.query(`ALTER TABLE "Drivers" DROP CONSTRAINT "FK_6f5323d19a6c07966acd7c4d7bc"`);
        await queryRunner.query(`ALTER TABLE "DriverVehicles" DROP CONSTRAINT "FK_f3f402fb120140e77068ecd8980"`);
        await queryRunner.query(`ALTER TABLE "DriverVehicles" DROP CONSTRAINT "FK_0c7d25eb04b9b73a6f59237deae"`);
        await queryRunner.query(`ALTER TABLE "Warehouses" DROP CONSTRAINT "FK_45cad077fe74dd6efe199865c65"`);
        await queryRunner.query(`ALTER TABLE "Warehouses" DROP CONSTRAINT "FK_313ea1d0c1741d0c8722d4a1e02"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_eaaf4085b89bf6ec4b1be465a1d"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_2eff86a49d8235e2a38b6641861"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_88a7467202367e2eca2bf02ba0a"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_e140ee76a77cff17dcd7c7f35f6"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_4c41d98e50f6b572f56271b027d"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_16bc25a3768d5768e540136e6b5"`);
        await queryRunner.query(`ALTER TABLE "WarehouseTransactions" DROP CONSTRAINT "FK_27e7064020bfec40f1276e925cf"`);
        await queryRunner.query(`ALTER TABLE "WarehouseDispatchHeaderStatusHistories" DROP CONSTRAINT "FK_500a306a3420581ea944cc33622"`);
        await queryRunner.query(`ALTER TABLE "Courses" DROP CONSTRAINT "FK_3dcb058a5ce8ce52b9125183ff1"`);
        await queryRunner.query(`ALTER TABLE "Courses" DROP CONSTRAINT "FK_ac4a39922892d1cdef24b5ae958"`);
        await queryRunner.query(`ALTER TABLE "Courses" DROP CONSTRAINT "FK_6a493e08c64ac2d8bc1b04410d5"`);
        await queryRunner.query(`ALTER TABLE "Teachers" DROP CONSTRAINT "FK_75c37917feecd381cc81daf6e0c"`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" DROP CONSTRAINT "FK_26475b404b7f5b51b9c62742cd0"`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" DROP CONSTRAINT "FK_96f33fcd95c12cee9be38e96eef"`);
        await queryRunner.query(`ALTER TABLE "CourseParticipants" DROP CONSTRAINT "FK_f227b8dd24547aad38315da4363"`);
        await queryRunner.query(`ALTER TABLE "Personnels" DROP CONSTRAINT "FK_66ab253e19118c601f2b6c7bb63"`);
        await queryRunner.query(`ALTER TABLE "Personnels" DROP CONSTRAINT "FK_6a33d281e251271dc27541024a4"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" DROP CONSTRAINT "FK_275f31e70efca4fd2c1deda8e98"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" DROP CONSTRAINT "FK_3c008e6d62328418bf077557fcd"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" DROP CONSTRAINT "FK_b99e020a4dbd6ae3faad9bf623a"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkPlaces" DROP CONSTRAINT "FK_bd94893b9f1bce11deadf720f82"`);
        await queryRunner.query(`ALTER TABLE "Rollcalls" DROP CONSTRAINT "FK_ecd705c0ace0b5ba311d7080c6d"`);
        await queryRunner.query(`ALTER TABLE "Rollcalls" DROP CONSTRAINT "FK_6ddd14193427fda89adac1d0222"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" DROP CONSTRAINT "FK_eb1a7bad33ba73d864bdc7abdd1"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" DROP CONSTRAINT "FK_1405427fa5a8cb9d05f55e722ad"`);
        await queryRunner.query(`ALTER TABLE "PersonnelWorkplaceProjects" DROP CONSTRAINT "FK_f924b5897182bbd669359f45e08"`);
        await queryRunner.query(`ALTER TABLE "Projects" DROP CONSTRAINT "FK_192d055806a34b9ddeb9b57e398"`);
        await queryRunner.query(`ALTER TABLE "Projects" DROP CONSTRAINT "FK_3586429252eb163412d2050e428"`);
        await queryRunner.query(`ALTER TABLE "Projects" DROP CONSTRAINT "FK_e8e2c96209b04158e75144a818c"`);
        await queryRunner.query(`ALTER TABLE "ProjectFirms" DROP CONSTRAINT "FK_9a10a829949ceaa7a06df72e19c"`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanings" DROP CONSTRAINT "FK_09be9a39c8284a424fc8dd16d3f"`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanings" DROP CONSTRAINT "FK_83cbf8c9c8304741c63fd7ffcfe"`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" DROP CONSTRAINT "FK_4404b264a9dee6cf67ff46aa4ed"`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" DROP CONSTRAINT "FK_c300cb927306e03def7b19c0721"`);
        await queryRunner.query(`ALTER TABLE "ProjectPlanningImplementation" DROP CONSTRAINT "FK_5ff3d4f1919c33f65dbb4601d1c"`);
        await queryRunner.query(`ALTER TABLE "ForceMajors" DROP CONSTRAINT "FK_717de6afef77504351ecba241e8"`);
        await queryRunner.query(`ALTER TABLE "UserRoles" DROP CONSTRAINT "FK_bd9e34313e9bb51d8b448f48f5c"`);
        await queryRunner.query(`ALTER TABLE "UserRoles" DROP CONSTRAINT "FK_eebd61741964d948d277e831c4c"`);
        await queryRunner.query(`ALTER TABLE "UserRoles" DROP CONSTRAINT "FK_c077e3fb81ccfcb9288697e1656"`);
        await queryRunner.query(`ALTER TABLE "Roles" DROP CONSTRAINT "FK_0edd9210272a77125e1fd27487e"`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" DROP CONSTRAINT "FK_6f81cd79160862327230e1a08e8"`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" DROP CONSTRAINT "FK_b0fe379e79d224cb3eee2fa51ba"`);
        await queryRunner.query(`ALTER TABLE "RoleSystemOperations" DROP CONSTRAINT "FK_ac37f5e143c3b1c9b08b37bb080"`);
        await queryRunner.query(`ALTER TABLE "SystemOperations" DROP CONSTRAINT "FK_b4c9f3fc0e013d1f8a8abf095a0"`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" DROP CONSTRAINT "FK_98369e843cc1f1e8dd768c9b0e0"`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" DROP CONSTRAINT "FK_0fe1d63425a53a2d6e0c90eb156"`);
        await queryRunner.query(`ALTER TABLE "UserSystemOperations" DROP CONSTRAINT "FK_74e6fb75c28608713a2f50f1f9c"`);
        await queryRunner.query(`ALTER TABLE "Positions" DROP CONSTRAINT "FK_f7d5a37a2c74d1841f0f04cf83a"`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" DROP CONSTRAINT "FK_95cb5143392e65e3bc67a399bc8"`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" DROP CONSTRAINT "FK_df7e970fa20232a30c493e02452"`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" DROP CONSTRAINT "FK_023b594fc4cf6f4a6464d64f5da"`);
        await queryRunner.query(`ALTER TABLE "PersonnelConsigneds" DROP CONSTRAINT "FK_f00ee557831be09903a41ea9df7"`);
        await queryRunner.query(`ALTER TABLE "Consignments" DROP CONSTRAINT "FK_9d41b6aad95b828d60f8cc3ba6f"`);
        await queryRunner.query(`ALTER TABLE "Leaves" DROP CONSTRAINT "FK_cec0c2d5020277c44de6a7f7744"`);
        await queryRunner.query(`ALTER TABLE "Leaves" DROP CONSTRAINT "FK_f2ea6ae585f729f7782dc40ca90"`);
        await queryRunner.query(`ALTER TABLE "LeaveHistories" DROP CONSTRAINT "FK_299ca76dbb9bdd886d3dcdee2c8"`);
        await queryRunner.query(`ALTER TABLE "LeaveHistories" DROP CONSTRAINT "FK_5d64bceaf7c06f3a973231151de"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_af233c3227588996ced5fa80dc5"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_886b3f368735726761671b3abd9"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_037533bef9cbe522cd83e91cc70"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_a0e7a6704be3e518ee9df935bcd"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_7fc960b55134f8214a4fe0c29fd"`);
        await queryRunner.query(`ALTER TABLE "StoreTransactions" DROP CONSTRAINT "FK_10e775973ac6d58d0e57b563d68"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptHeaders" DROP CONSTRAINT "FK_2a173697761b0b9c4e507bb9f66"`);
        await queryRunner.query(`ALTER TABLE "StoreReceiptHeaders" DROP CONSTRAINT "FK_06419874f370dd380f6dcd1d1ab"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaderStatusHistories" DROP CONSTRAINT "FK_4f0b014783bb229a7fbdacbceaa"`);
        await queryRunner.query(`ALTER TABLE "StoreDispatchHeaderStatusHistories" DROP CONSTRAINT "FK_2ae4752c69cd9582e8515d62e2c"`);
        await queryRunner.query(`DROP INDEX "public"."Works_pkey"`);
        await queryRunner.query(`DROP TABLE "Works"`);
        await queryRunner.query(`DROP INDEX "public"."ChannelRows_pkey"`);
        await queryRunner.query(`DROP TABLE "ChannelRows"`);
        await queryRunner.query(`DROP INDEX "public"."ChannelRowItems_pkey"`);
        await queryRunner.query(`DROP TABLE "ChannelRowItems"`);
        await queryRunner.query(`DROP INDEX "public"."Items_pkey"`);
        await queryRunner.query(`DROP TABLE "Items"`);
        await queryRunner.query(`DROP INDEX "public"."InvoiceDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "InvoiceDetails"`);
        await queryRunner.query(`DROP INDEX "public"."InvoiceHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "InvoiceHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."InvoiceHeaderStatusHistories_pkey"`);
        await queryRunner.query(`DROP TABLE "InvoiceHeaderStatusHistories"`);
        await queryRunner.query(`DROP INDEX "public"."Users_pkey"`);
        await queryRunner.query(`DROP TABLE "Users"`);
        await queryRunner.query(`DROP INDEX "public"."TenderDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "TenderDetails"`);
        await queryRunner.query(`DROP INDEX "public"."TenderHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "TenderHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."ProductTypes_pkey"`);
        await queryRunner.query(`DROP TABLE "ProductTypes"`);
        await queryRunner.query(`DROP INDEX "public"."Networks_pkey"`);
        await queryRunner.query(`DROP TABLE "Networks"`);
        await queryRunner.query(`DROP INDEX "public"."TransmissionRows_pkey"`);
        await queryRunner.query(`DROP TABLE "TransmissionRows"`);
        await queryRunner.query(`DROP INDEX "public"."TransmissionRowItmes_pkey"`);
        await queryRunner.query(`DROP TABLE "TransmissionRowItmes"`);
        await queryRunner.query(`DROP INDEX "public"."OrderHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "OrderHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."OrderHeaderStatusHistories_pkey"`);
        await queryRunner.query(`DROP TABLE "OrderHeaderStatusHistories"`);
        await queryRunner.query(`DROP INDEX "public"."OrderDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "OrderDetails"`);
        await queryRunner.query(`DROP INDEX "public"."ItemUnits_pkey"`);
        await queryRunner.query(`DROP TABLE "ItemUnits"`);
        await queryRunner.query(`DROP INDEX "public"."Categories_pkey"`);
        await queryRunner.query(`DROP TABLE "Categories"`);
        await queryRunner.query(`DROP INDEX "public"."CarFuels_pkey"`);
        await queryRunner.query(`DROP TABLE "CarFuels"`);
        await queryRunner.query(`DROP INDEX "public"."ConsignedCars_pkey"`);
        await queryRunner.query(`DROP TABLE "ConsignedCars"`);
        await queryRunner.query(`DROP INDEX "public"."CarWarhouseDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "CarWarhouseDetails"`);
        await queryRunner.query(`DROP INDEX "public"."CarWarhouses_pkey"`);
        await queryRunner.query(`DROP TABLE "CarWarhouses"`);
        await queryRunner.query(`DROP INDEX "public"."Regions_pkey"`);
        await queryRunner.query(`DROP TABLE "Regions"`);
        await queryRunner.query(`DROP INDEX "public"."Providers_pkey"`);
        await queryRunner.query(`DROP TABLE "Providers"`);
        await queryRunner.query(`DROP INDEX "public"."ReceiptDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "ReceiptDetails"`);
        await queryRunner.query(`DROP INDEX "public"."ReceiptHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "ReceiptHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."WarehouseDispatchDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "WarehouseDispatchDetails"`);
        await queryRunner.query(`DROP INDEX "public"."StoreReceiptDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreReceiptDetails"`);
        await queryRunner.query(`DROP INDEX "public"."StoreDispatchDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreDispatchDetails"`);
        await queryRunner.query(`DROP INDEX "public"."StoreDispatchHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreDispatchHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."Stores_pkey"`);
        await queryRunner.query(`DROP TABLE "Stores"`);
        await queryRunner.query(`DROP INDEX "public"."Workhouses_pkey"`);
        await queryRunner.query(`DROP TABLE "Workhouses"`);
        await queryRunner.query(`DROP INDEX "public"."WorkhouseDetails_pkey"`);
        await queryRunner.query(`DROP TABLE "WorkhouseDetails"`);
        await queryRunner.query(`DROP INDEX "public"."WarehouseDispatchHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "WarehouseDispatchHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."Drivers_pkey"`);
        await queryRunner.query(`DROP TABLE "Drivers"`);
        await queryRunner.query(`DROP INDEX "public"."DriverVehicles_pkey"`);
        await queryRunner.query(`DROP TABLE "DriverVehicles"`);
        await queryRunner.query(`DROP INDEX "public"."Warehouses_pkey"`);
        await queryRunner.query(`DROP TABLE "Warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."WarehouseTransactions_pkey"`);
        await queryRunner.query(`DROP TABLE "WarehouseTransactions"`);
        await queryRunner.query(`DROP INDEX "public"."WarehouseDispatchHeaderStatusHistories_pkey"`);
        await queryRunner.query(`DROP TABLE "WarehouseDispatchHeaderStatusHistories"`);
        await queryRunner.query(`DROP INDEX "public"."Courses_pkey"`);
        await queryRunner.query(`DROP TABLE "Courses"`);
        await queryRunner.query(`DROP INDEX "public"."Teachers_pkey"`);
        await queryRunner.query(`DROP TABLE "Teachers"`);
        await queryRunner.query(`DROP INDEX "public"."CourseParticipants_pkey"`);
        await queryRunner.query(`DROP TABLE "CourseParticipants"`);
        await queryRunner.query(`DROP INDEX "public"."Personnels_pkey"`);
        await queryRunner.query(`DROP TABLE "Personnels"`);
        await queryRunner.query(`DROP INDEX "public"."PersonnelWorkPlaces_pkey"`);
        await queryRunner.query(`DROP TABLE "PersonnelWorkPlaces"`);
        await queryRunner.query(`DROP INDEX "public"."Rollcalls_pkey"`);
        await queryRunner.query(`DROP TABLE "Rollcalls"`);
        await queryRunner.query(`DROP INDEX "public"."PersonnelWorkplaceProjects_pkey"`);
        await queryRunner.query(`DROP TABLE "PersonnelWorkplaceProjects"`);
        await queryRunner.query(`DROP INDEX "public"."Projects_pkey"`);
        await queryRunner.query(`DROP TABLE "Projects"`);
        await queryRunner.query(`DROP INDEX "public"."ProjectFirms_pkey"`);
        await queryRunner.query(`DROP TABLE "ProjectFirms"`);
        await queryRunner.query(`DROP INDEX "public"."ProjectPlanings_pkey"`);
        await queryRunner.query(`DROP TABLE "ProjectPlanings"`);
        await queryRunner.query(`DROP INDEX "public"."ProjectPlanningImplementation_pkey"`);
        await queryRunner.query(`DROP TABLE "ProjectPlanningImplementation"`);
        await queryRunner.query(`DROP INDEX "public"."ForceMajors_pkey"`);
        await queryRunner.query(`DROP TABLE "ForceMajors"`);
        await queryRunner.query(`DROP INDEX "public"."UserRoles_pkey"`);
        await queryRunner.query(`DROP TABLE "UserRoles"`);
        await queryRunner.query(`DROP INDEX "public"."Roles_pkey"`);
        await queryRunner.query(`DROP TABLE "Roles"`);
        await queryRunner.query(`DROP INDEX "public"."RoleSystemOperations_pkey"`);
        await queryRunner.query(`DROP TABLE "RoleSystemOperations"`);
        await queryRunner.query(`DROP INDEX "public"."SystemOperations_pkey"`);
        await queryRunner.query(`DROP TABLE "SystemOperations"`);
        await queryRunner.query(`DROP INDEX "public"."UserSystemOperations_pkey"`);
        await queryRunner.query(`DROP TABLE "UserSystemOperations"`);
        await queryRunner.query(`DROP INDEX "public"."Positions_pkey"`);
        await queryRunner.query(`DROP TABLE "Positions"`);
        await queryRunner.query(`DROP INDEX "public"."PersonnelConsigneds_pkey"`);
        await queryRunner.query(`DROP TABLE "PersonnelConsigneds"`);
        await queryRunner.query(`DROP INDEX "public"."Consignments_pkey"`);
        await queryRunner.query(`DROP TABLE "Consignments"`);
        await queryRunner.query(`DROP INDEX "public"."Leaves_pkey"`);
        await queryRunner.query(`DROP TABLE "Leaves"`);
        await queryRunner.query(`DROP INDEX "public"."LeaveHistories_pkey"`);
        await queryRunner.query(`DROP TABLE "LeaveHistories"`);
        await queryRunner.query(`DROP INDEX "public"."StoreTransactions_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreTransactions"`);
        await queryRunner.query(`DROP INDEX "public"."StoreReceiptHeaders_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreReceiptHeaders"`);
        await queryRunner.query(`DROP INDEX "public"."StoreDispatchHeaderStatusHistories_pkey"`);
        await queryRunner.query(`DROP TABLE "StoreDispatchHeaderStatusHistories"`);
    }

}
